# Generated by Django 4.2.11 on 2024-03-31 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_blogpagetag_blogpage_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpagetag",
            old_name="content_block",
            new_name="content_object",
        ),
    ]
